#28 - Implement stepper Countries location service
Project-Based-10-24-vk/BackEnd pull request #44
Opened 2024-10-20 14:06 UTC by melyasanya

Created route, controller and service for getting countries using CountriesAPI. You need to copy from env file two last variables to make it work. Also created test and added info to swagger

2024-10-20 16:20 UTC, natamrshn requested changes
Please, resolve conflicts on branch

2024-10-20 18:37 UTC, zim89 approved these changes

2024-10-21 16:17 UTC, AntonRomanov999 approved these changes

2024-10-22 12:18 UTC, nadraharr approved these changes

2024-10-23 15:55 UTC, VoitV approved these changes

2024-10-23 16:45 UTC, vlad-khrychov approved these changes

2024-10-24 11:19 UTC, merged