#29 - Implement stepper Cities location service
Project-Based-10-24-vk/BackEnd pull request #45
Opened 2024-10-20 15:31 UTC by melyasanya

This branch branched from another pr, where i created locations route. I will mark with comments everything that has been changed for this task. I will delete comments when pr will be approved

Created route, controller and service for cities search using CountriesAPI. Also added info to swagger and created tests

2024-10-20 17:05 UTC, zim89 approved these changes

2024-10-21 07:47 UTC, natamrshn requested changes
Please, resolve conflicts on your branch

2024-10-21 14:27 UTC, natamrshn approved these changes

2024-10-22 12:17 UTC, nadraharr approved these changes

2024-10-22 12:25 UTC, AntonRomanov999 approved these changes

2024-10-23 15:57 UTC, VoitV approved these changes

2024-10-23 16:48 UTC, vlad-khrychov approved these changes

2024-10-24 11:20 UTC, merged